name: share-preview 
base: core22 
adopt-info: share-preview
grade: stable 
confinement: strict 
website: https://github.com/soumyaDghosh/share-preview-snap
source-code: https://github.com/rafaelmardojai/share-preview
issues: https://github.com/soumyaDghosh/share-preview-snap/issues
license: GPL-3.0
title: Share Preview
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  rustup:
    plugin: nil
    build-packages: [ wget ]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  share-preview:
    after: [ rustup ]
    plugin: meson
    source: https://github.com/rafaelmardojai/share-preview.git
    source-tag: '0.5.0'
    source-depth: 1
    build-packages:
      - libssl-dev
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    meson-parameters:
      - --prefix=/snap/share-preview/current/usr
    organize:
      snap/share-preview/current: .
    parse-info: [ usr/share/metainfo/com.rafaelmardojai.SharePreview.metainfo.xml ]
  cleanup:
    after: 
      - share-preview
      - rustup
    plugin: nil
    build-snaps:  
      - gnome-42-2204
      - gtk-common-themes
      - core22
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "gtk-common-themes" "core22"; do
      cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done  


slots:
  share-preview:
    interface: dbus
    bus: session
    name: com.rafaelmardojai.SharePreview
apps:
  share-preview:
    command: usr/bin/share-preview
    desktop: usr/share/applications/com.rafaelmardojai.SharePreview.desktop
    common-id: com.rafaelmardojai.SharePreview
    extensions: [ gnome ]
    plugs:
      - network
      - network-observe
